# config file version
apiVersion: 1

# datasources
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: P@55w0rd
    jsonData:
      sslmode: 'disable'
